//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package no.nav.avtaltmelding.trygderetten.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for navMappe complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="navMappe">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="saksnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="kravfremsettelsesdato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         <element name="paaanketVedtaksdato" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         <element name="lovhenvisning" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         <element name="tidligereITROgOpphevetHenvist" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="gjenopptak" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="forsterketRett" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="ettersendelse" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "navMappe", propOrder = {
    "saksnummer",
    "kravfremsettelsesdato",
    "paaanketVedtaksdato",
    "lovhenvisning",
    "tidligereITROgOpphevetHenvist",
    "gjenopptak",
    "forsterketRett",
    "ettersendelse"
})
@XmlRootElement
public class NavMappe {

    @XmlElement(required = true)
    protected String saksnummer;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar kravfremsettelsesdato;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paaanketVedtaksdato;
    @XmlElement(required = true)
    protected List<String> lovhenvisning;
    protected Boolean tidligereITROgOpphevetHenvist;
    protected Boolean gjenopptak;
    protected boolean forsterketRett;
    protected boolean ettersendelse;

    /**
     * Gets the value of the saksnummer property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSaksnummer() {
        return saksnummer;
    }

    /**
     * Sets the value of the saksnummer property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSaksnummer(String value) {
        this.saksnummer = value;
    }

    public NavMappe useSaksnummer(String value) {
        setSaksnummer(value);
        return this;
    }

    /**
     * Gets the value of the kravfremsettelsesdato property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getKravfremsettelsesdato() {
        return kravfremsettelsesdato;
    }

    /**
     * Sets the value of the kravfremsettelsesdato property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setKravfremsettelsesdato(XMLGregorianCalendar value) {
        this.kravfremsettelsesdato = value;
    }

    public NavMappe useKravfremsettelsesdato(XMLGregorianCalendar value) {
        setKravfremsettelsesdato(value);
        return this;
    }

    /**
     * Gets the value of the paaanketVedtaksdato property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getPaaanketVedtaksdato() {
        return paaanketVedtaksdato;
    }

    /**
     * Sets the value of the paaanketVedtaksdato property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setPaaanketVedtaksdato(XMLGregorianCalendar value) {
        this.paaanketVedtaksdato = value;
    }

    public NavMappe usePaaanketVedtaksdato(XMLGregorianCalendar value) {
        setPaaanketVedtaksdato(value);
        return this;
    }

    /**
     * Gets the value of the tidligereITROgOpphevetHenvist property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isTidligereITROgOpphevetHenvist() {
        return tidligereITROgOpphevetHenvist;
    }

    /**
     * Sets the value of the tidligereITROgOpphevetHenvist property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setTidligereITROgOpphevetHenvist(Boolean value) {
        this.tidligereITROgOpphevetHenvist = value;
    }

    public NavMappe useTidligereITROgOpphevetHenvist(Boolean value) {
        setTidligereITROgOpphevetHenvist(value);
        return this;
    }

    /**
     * Gets the value of the gjenopptak property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isGjenopptak() {
        return gjenopptak;
    }

    /**
     * Sets the value of the gjenopptak property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setGjenopptak(Boolean value) {
        this.gjenopptak = value;
    }

    public NavMappe useGjenopptak(Boolean value) {
        setGjenopptak(value);
        return this;
    }

    /**
     * Gets the value of the forsterketRett property.
     *
     */
    public boolean isForsterketRett() {
        return forsterketRett;
    }

    /**
     * Sets the value of the forsterketRett property.
     *
     */
    public void setForsterketRett(boolean value) {
        this.forsterketRett = value;
    }

    public NavMappe useForsterketRett(boolean value) {
        setForsterketRett(value);
        return this;
    }

    /**
     * Gets the value of the ettersendelse property.
     *
     */
    public boolean isEttersendelse() {
        return ettersendelse;
    }

    /**
     * Sets the value of the ettersendelse property.
     *
     */
    public void setEttersendelse(boolean value) {
        this.ettersendelse = value;
    }

    public NavMappe useEttersendelse(boolean value) {
        setEttersendelse(value);
        return this;
    }

    /**
     * Gets the value of the lovhenvisning property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the object.
     *
     * <p>For example, to add a new item, do as follows:
     * <pre>
     * getLovhenvisning().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     * @return
     *     The value of the lovhenvisning property.
     */
    public List<String> getLovhenvisning() {
        if (lovhenvisning == null) {
            lovhenvisning = new ArrayList<>();
        }
        return this.lovhenvisning;
    }

}
