//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for arkivnotat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="arkivnotat">
 *   <complexContent>
 *     <extension base="{http://www.arkivverket.no/standarder/noark5/arkivmelding}registrering">
 *       <sequence>
 *         <element name="dokumentetsDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}dokumentetsDato" minOccurs="0"/>
 *         <element name="mottattDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}mottattDato" minOccurs="0"/>
 *         <element name="sendtDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}sendtDato" minOccurs="0"/>
 *         <element name="forfallsdato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}forfallsdato" minOccurs="0"/>
 *         <element name="offentlighetsvurdertDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}offentlighetsvurdertDato" minOccurs="0"/>
 *         <element name="antallVedlegg" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}antallVedlegg" minOccurs="0"/>
 *         <element name="utlaantDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}utlaantDato" minOccurs="0"/>
 *         <element name="utlaantTil" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}utlaantTil" minOccurs="0"/>
 *         <element name="dokumentflyt" type="{http://www.arkivverket.no/standarder/noark5/arkivmelding}dokumentflyt" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arkivnotat", propOrder = {
    "dokumentetsDato",
    "mottattDato",
    "sendtDato",
    "forfallsdato",
    "offentlighetsvurdertDato",
    "antallVedlegg",
    "utlaantDato",
    "utlaantTil",
    "dokumentflyt"
})
public class Arkivnotat
    extends Registrering
{

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dokumentetsDato;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mottattDato;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sendtDato;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar forfallsdato;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar offentlighetsvurdertDato;
    protected BigInteger antallVedlegg;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar utlaantDato;
    protected String utlaantTil;
    protected List<Dokumentflyt> dokumentflyt;

    @Override
    public Arkivnotat useKorrespondansepart(Collection<Korrespondansepart> values) {
        if (values!= null) {
            getKorrespondansepart().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useKorrespondansepart(Korrespondansepart... values) {
        if (values!= null) {
            for (Korrespondansepart value: values) {
                getKorrespondansepart().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useKryssreferanse(Collection<Kryssreferanse> values) {
        if (values!= null) {
            getKryssreferanse().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useKryssreferanse(Kryssreferanse... values) {
        if (values!= null) {
            for (Kryssreferanse value: values) {
                getKryssreferanse().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useMerknad(Collection<Merknad> values) {
        if (values!= null) {
            getMerknad().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useMerknad(Merknad... values) {
        if (values!= null) {
            for (Merknad value: values) {
                getMerknad().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useVirksomhetsspesifikkeMetadata(Object value) {
        setVirksomhetsspesifikkeMetadata(value);
        return this;
    }

    @Override
    public Arkivnotat useOppbevaringssted(Collection<String> values) {
        if (values!= null) {
            getOppbevaringssted().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useOppbevaringssted(String... values) {
        if (values!= null) {
            for (String value: values) {
                getOppbevaringssted().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useDokumentmedium(String value) {
        setDokumentmedium(value);
        return this;
    }

    @Override
    public Arkivnotat useForfatter(Collection<String> values) {
        if (values!= null) {
            getForfatter().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useForfatter(String... values) {
        if (values!= null) {
            for (String value: values) {
                getForfatter().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useNoekkelord(Collection<String> values) {
        if (values!= null) {
            getNoekkelord().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useNoekkelord(String... values) {
        if (values!= null) {
            for (String value: values) {
                getNoekkelord().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useBeskrivelse(String value) {
        setBeskrivelse(value);
        return this;
    }

    @Override
    public Arkivnotat useOffentligTittel(String value) {
        setOffentligTittel(value);
        return this;
    }

    @Override
    public Arkivnotat useTittel(String value) {
        setTittel(value);
        return this;
    }

    @Override
    public Arkivnotat useRegistreringsID(String value) {
        setRegistreringsID(value);
        return this;
    }

    @Override
    public Arkivnotat useDokumentbeskrivelse(Collection<Dokumentbeskrivelse> values) {
        if (values!= null) {
            getDokumentbeskrivelse().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat useDokumentbeskrivelse(Dokumentbeskrivelse... values) {
        if (values!= null) {
            for (Dokumentbeskrivelse value: values) {
                getDokumentbeskrivelse().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useGradering(Gradering value) {
        setGradering(value);
        return this;
    }

    @Override
    public Arkivnotat useSkjerming(Skjerming value) {
        setSkjerming(value);
        return this;
    }

    @Override
    public Arkivnotat usePart(Collection<Part> values) {
        if (values!= null) {
            getPart().addAll(values);
        }
        return this;
    }

    @Override
    public Arkivnotat usePart(Part... values) {
        if (values!= null) {
            for (Part value: values) {
                getPart().add(value);
            }
        }
        return this;
    }

    @Override
    public Arkivnotat useReferanseArkivdel(String value) {
        setReferanseArkivdel(value);
        return this;
    }

    @Override
    public Arkivnotat useReferanseForelderMappe(String value) {
        setReferanseForelderMappe(value);
        return this;
    }

    @Override
    public Arkivnotat useArkivertAv(String value) {
        setArkivertAv(value);
        return this;
    }

    @Override
    public Arkivnotat useArkivertDato(XMLGregorianCalendar value) {
        setArkivertDato(value);
        return this;
    }

    @Override
    public Arkivnotat useOpprettetAv(String value) {
        setOpprettetAv(value);
        return this;
    }

    @Override
    public Arkivnotat useOpprettetDato(XMLGregorianCalendar value) {
        setOpprettetDato(value);
        return this;
    }

    @Override
    public Arkivnotat useSystemID(SystemID value) {
        setSystemID(value);
        return this;
    }

    /**
     * Gets the value of the dokumentetsDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDokumentetsDato() {
        return dokumentetsDato;
    }

    /**
     * Sets the value of the dokumentetsDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDokumentetsDato(XMLGregorianCalendar value) {
        this.dokumentetsDato = value;
    }

    public Arkivnotat useDokumentetsDato(XMLGregorianCalendar value) {
        setDokumentetsDato(value);
        return this;
    }

    /**
     * Gets the value of the mottattDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMottattDato() {
        return mottattDato;
    }

    /**
     * Sets the value of the mottattDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMottattDato(XMLGregorianCalendar value) {
        this.mottattDato = value;
    }

    public Arkivnotat useMottattDato(XMLGregorianCalendar value) {
        setMottattDato(value);
        return this;
    }

    /**
     * Gets the value of the sendtDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSendtDato() {
        return sendtDato;
    }

    /**
     * Sets the value of the sendtDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSendtDato(XMLGregorianCalendar value) {
        this.sendtDato = value;
    }

    public Arkivnotat useSendtDato(XMLGregorianCalendar value) {
        setSendtDato(value);
        return this;
    }

    /**
     * Gets the value of the forfallsdato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getForfallsdato() {
        return forfallsdato;
    }

    /**
     * Sets the value of the forfallsdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setForfallsdato(XMLGregorianCalendar value) {
        this.forfallsdato = value;
    }

    public Arkivnotat useForfallsdato(XMLGregorianCalendar value) {
        setForfallsdato(value);
        return this;
    }

    /**
     * Gets the value of the offentlighetsvurdertDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOffentlighetsvurdertDato() {
        return offentlighetsvurdertDato;
    }

    /**
     * Sets the value of the offentlighetsvurdertDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOffentlighetsvurdertDato(XMLGregorianCalendar value) {
        this.offentlighetsvurdertDato = value;
    }

    public Arkivnotat useOffentlighetsvurdertDato(XMLGregorianCalendar value) {
        setOffentlighetsvurdertDato(value);
        return this;
    }

    /**
     * Gets the value of the antallVedlegg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallVedlegg() {
        return antallVedlegg;
    }

    /**
     * Sets the value of the antallVedlegg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallVedlegg(BigInteger value) {
        this.antallVedlegg = value;
    }

    public Arkivnotat useAntallVedlegg(BigInteger value) {
        setAntallVedlegg(value);
        return this;
    }

    /**
     * Gets the value of the utlaantDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUtlaantDato() {
        return utlaantDato;
    }

    /**
     * Sets the value of the utlaantDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUtlaantDato(XMLGregorianCalendar value) {
        this.utlaantDato = value;
    }

    public Arkivnotat useUtlaantDato(XMLGregorianCalendar value) {
        setUtlaantDato(value);
        return this;
    }

    /**
     * Gets the value of the utlaantTil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtlaantTil() {
        return utlaantTil;
    }

    /**
     * Sets the value of the utlaantTil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtlaantTil(String value) {
        this.utlaantTil = value;
    }

    public Arkivnotat useUtlaantTil(String value) {
        setUtlaantTil(value);
        return this;
    }

    /**
     * Gets the value of the dokumentflyt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the dokumentflyt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDokumentflyt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dokumentflyt }
     * 
     * 
     * @return
     *     The value of the dokumentflyt property.
     */
    public List<Dokumentflyt> getDokumentflyt() {
        if (dokumentflyt == null) {
            dokumentflyt = new ArrayList<>();
        }
        return this.dokumentflyt;
    }

    public Arkivnotat useDokumentflyt(Collection<Dokumentflyt> values) {
        if (values!= null) {
            getDokumentflyt().addAll(values);
        }
        return this;
    }

    public Arkivnotat useDokumentflyt(Dokumentflyt... values) {
        if (values!= null) {
            for (Dokumentflyt value: values) {
                getDokumentflyt().add(value);
            }
        }
        return this;
    }

}
