//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for arkivmelding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="arkivmelding">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="system" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="meldingId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="tidspunkt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         <element name="antallFiler" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         <choice>
 *           <element name="mappe" type="{http://www.arkivverket.no/standarder/noark5/arkivmelding}mappe" maxOccurs="unbounded" minOccurs="0"/>
 *           <element name="registrering" type="{http://www.arkivverket.no/standarder/noark5/arkivmelding}registrering" maxOccurs="unbounded" minOccurs="0"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arkivmelding", propOrder = {
    "system",
    "meldingId",
    "tidspunkt",
    "antallFiler",
    "mappe",
    "registrering"
})
@XmlRootElement
public class Arkivmelding {

    @XmlElement(required = true)
    protected String system;
    @XmlElement(required = true)
    protected String meldingId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tidspunkt;
    protected int antallFiler;
    protected List<Mappe> mappe;
    protected List<Registrering> registrering;

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystem(String value) {
        this.system = value;
    }

    public Arkivmelding useSystem(String value) {
        setSystem(value);
        return this;
    }

    /**
     * Gets the value of the meldingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeldingId() {
        return meldingId;
    }

    /**
     * Sets the value of the meldingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeldingId(String value) {
        this.meldingId = value;
    }

    public Arkivmelding useMeldingId(String value) {
        setMeldingId(value);
        return this;
    }

    /**
     * Gets the value of the tidspunkt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTidspunkt() {
        return tidspunkt;
    }

    /**
     * Sets the value of the tidspunkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTidspunkt(XMLGregorianCalendar value) {
        this.tidspunkt = value;
    }

    public Arkivmelding useTidspunkt(XMLGregorianCalendar value) {
        setTidspunkt(value);
        return this;
    }

    /**
     * Gets the value of the antallFiler property.
     * 
     */
    public int getAntallFiler() {
        return antallFiler;
    }

    /**
     * Sets the value of the antallFiler property.
     * 
     */
    public void setAntallFiler(int value) {
        this.antallFiler = value;
    }

    public Arkivmelding useAntallFiler(int value) {
        setAntallFiler(value);
        return this;
    }

    /**
     * Gets the value of the mappe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the mappe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMappe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mappe }
     * 
     * 
     * @return
     *     The value of the mappe property.
     */
    public List<Mappe> getMappe() {
        if (mappe == null) {
            mappe = new ArrayList<>();
        }
        return this.mappe;
    }

    public Arkivmelding useMappe(Collection<Mappe> values) {
        if (values!= null) {
            getMappe().addAll(values);
        }
        return this;
    }

    public Arkivmelding useMappe(Mappe... values) {
        if (values!= null) {
            for (Mappe value: values) {
                getMappe().add(value);
            }
        }
        return this;
    }

    /**
     * Gets the value of the registrering property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the registrering property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegistrering().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Registrering }
     * 
     * 
     * @return
     *     The value of the registrering property.
     */
    public List<Registrering> getRegistrering() {
        if (registrering == null) {
            registrering = new ArrayList<>();
        }
        return this.registrering;
    }

    public Arkivmelding useRegistrering(Collection<Registrering> values) {
        if (values!= null) {
            getRegistrering().addAll(values);
        }
        return this;
    }

    public Arkivmelding useRegistrering(Registrering... values) {
        if (values!= null) {
            for (Registrering value: values) {
                getRegistrering().add(value);
            }
        }
        return this;
    }

}
