//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for avskrivning complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="avskrivning">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="avskrivningsdato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}avskrivningsdato"/>
 *         <element name="avskrevetAv" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}avskrevetAv"/>
 *         <element name="avskrivningsmaate" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}avskrivningsmaate"/>
 *         <element name="referanseAvskrivesAvJournalpost" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}referanseAvskrivesAvJournalpost" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "avskrivning", propOrder = {
    "avskrivningsdato",
    "avskrevetAv",
    "avskrivningsmaate",
    "referanseAvskrivesAvJournalpost"
})
public class Avskrivning {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar avskrivningsdato;
    @XmlElement(required = true)
    protected String avskrevetAv;
    @XmlElement(required = true)
    protected String avskrivningsmaate;
    protected String referanseAvskrivesAvJournalpost;

    /**
     * Gets the value of the avskrivningsdato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvskrivningsdato() {
        return avskrivningsdato;
    }

    /**
     * Sets the value of the avskrivningsdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvskrivningsdato(XMLGregorianCalendar value) {
        this.avskrivningsdato = value;
    }

    public Avskrivning useAvskrivningsdato(XMLGregorianCalendar value) {
        setAvskrivningsdato(value);
        return this;
    }

    /**
     * Gets the value of the avskrevetAv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvskrevetAv() {
        return avskrevetAv;
    }

    /**
     * Sets the value of the avskrevetAv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvskrevetAv(String value) {
        this.avskrevetAv = value;
    }

    public Avskrivning useAvskrevetAv(String value) {
        setAvskrevetAv(value);
        return this;
    }

    /**
     * Gets the value of the avskrivningsmaate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvskrivningsmaate() {
        return avskrivningsmaate;
    }

    /**
     * Sets the value of the avskrivningsmaate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvskrivningsmaate(String value) {
        this.avskrivningsmaate = value;
    }

    public Avskrivning useAvskrivningsmaate(String value) {
        setAvskrivningsmaate(value);
        return this;
    }

    /**
     * Gets the value of the referanseAvskrivesAvJournalpost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferanseAvskrivesAvJournalpost() {
        return referanseAvskrivesAvJournalpost;
    }

    /**
     * Sets the value of the referanseAvskrivesAvJournalpost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferanseAvskrivesAvJournalpost(String value) {
        this.referanseAvskrivesAvJournalpost = value;
    }

    public Avskrivning useReferanseAvskrivesAvJournalpost(String value) {
        setReferanseAvskrivesAvJournalpost(value);
        return this;
    }

}
