//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for dokumentflyt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="dokumentflyt">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="flytTil" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}flytTil"/>
 *         <element name="flytFra" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}flytFra"/>
 *         <element name="flytMottattDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}flytMottattDato"/>
 *         <element name="flytSendtDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}flytSendtDato"/>
 *         <element name="flytStatus" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}flytStatus"/>
 *         <element name="flytMerknad" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}flytMerknad" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dokumentflyt", propOrder = {
    "flytTil",
    "flytFra",
    "flytMottattDato",
    "flytSendtDato",
    "flytStatus",
    "flytMerknad"
})
public class Dokumentflyt {

    @XmlElement(required = true)
    protected String flytTil;
    @XmlElement(required = true)
    protected String flytFra;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar flytMottattDato;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar flytSendtDato;
    @XmlElement(required = true)
    protected String flytStatus;
    protected String flytMerknad;

    /**
     * Gets the value of the flytTil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlytTil() {
        return flytTil;
    }

    /**
     * Sets the value of the flytTil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlytTil(String value) {
        this.flytTil = value;
    }

    public Dokumentflyt useFlytTil(String value) {
        setFlytTil(value);
        return this;
    }

    /**
     * Gets the value of the flytFra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlytFra() {
        return flytFra;
    }

    /**
     * Sets the value of the flytFra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlytFra(String value) {
        this.flytFra = value;
    }

    public Dokumentflyt useFlytFra(String value) {
        setFlytFra(value);
        return this;
    }

    /**
     * Gets the value of the flytMottattDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFlytMottattDato() {
        return flytMottattDato;
    }

    /**
     * Sets the value of the flytMottattDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFlytMottattDato(XMLGregorianCalendar value) {
        this.flytMottattDato = value;
    }

    public Dokumentflyt useFlytMottattDato(XMLGregorianCalendar value) {
        setFlytMottattDato(value);
        return this;
    }

    /**
     * Gets the value of the flytSendtDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFlytSendtDato() {
        return flytSendtDato;
    }

    /**
     * Sets the value of the flytSendtDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFlytSendtDato(XMLGregorianCalendar value) {
        this.flytSendtDato = value;
    }

    public Dokumentflyt useFlytSendtDato(XMLGregorianCalendar value) {
        setFlytSendtDato(value);
        return this;
    }

    /**
     * Gets the value of the flytStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlytStatus() {
        return flytStatus;
    }

    /**
     * Sets the value of the flytStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlytStatus(String value) {
        this.flytStatus = value;
    }

    public Dokumentflyt useFlytStatus(String value) {
        setFlytStatus(value);
        return this;
    }

    /**
     * Gets the value of the flytMerknad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlytMerknad() {
        return flytMerknad;
    }

    /**
     * Sets the value of the flytMerknad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlytMerknad(String value) {
        this.flytMerknad = value;
    }

    public Dokumentflyt useFlytMerknad(String value) {
        setFlytMerknad(value);
        return this;
    }

}
