//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnhetsidentifikatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="EnhetsidentifikatorType">
 *   <complexContent>
 *     <extension base="{http://www.arkivverket.no/standarder/noark5/arkivmelding}AbstraktNasjonalidentifikatorType">
 *       <sequence>
 *         <element name="organisasjonsnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnhetsidentifikatorType", propOrder = {
    "organisasjonsnummer"
})
public class EnhetsidentifikatorType
    extends AbstraktNasjonalidentifikatorType
{

    @XmlElement(required = true)
    protected String organisasjonsnummer;

    @Override
    public EnhetsidentifikatorType useBeskrivelse(String value) {
        setBeskrivelse(value);
        return this;
    }

    @Override
    public EnhetsidentifikatorType useSystemID(String value) {
        setSystemID(value);
        return this;
    }

    /**
     * Gets the value of the organisasjonsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisasjonsnummer() {
        return organisasjonsnummer;
    }

    /**
     * Sets the value of the organisasjonsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisasjonsnummer(String value) {
        this.organisasjonsnummer = value;
    }

    public EnhetsidentifikatorType useOrganisasjonsnummer(String value) {
        setOrganisasjonsnummer(value);
        return this;
    }

}
