//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FoedselsnummerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="FoedselsnummerType">
 *   <complexContent>
 *     <extension base="{http://www.arkivverket.no/standarder/noark5/arkivmelding}AbstraktPersonidentifikatorType">
 *       <sequence>
 *         <element name="foedselsnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FoedselsnummerType", propOrder = {
    "foedselsnummer"
})
public class FoedselsnummerType
    extends AbstraktPersonidentifikatorType
{

    @XmlElement(required = true)
    protected String foedselsnummer;

    @Override
    public FoedselsnummerType useBeskrivelse(String value) {
        setBeskrivelse(value);
        return this;
    }

    @Override
    public FoedselsnummerType useSystemID(String value) {
        setSystemID(value);
        return this;
    }

    /**
     * Gets the value of the foedselsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoedselsnummer() {
        return foedselsnummer;
    }

    /**
     * Sets the value of the foedselsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoedselsnummer(String value) {
        this.foedselsnummer = value;
    }

    public FoedselsnummerType useFoedselsnummer(String value) {
        setFoedselsnummer(value);
        return this;
    }

}
