//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for journalpost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="journalpost">
 *   <complexContent>
 *     <extension base="{http://www.arkivverket.no/standarder/noark5/arkivmelding}registrering">
 *       <sequence>
 *         <element name="journalaar" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journalaar" minOccurs="0"/>
 *         <element name="journalsekvensnummer" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journalsekvensnummer" minOccurs="0"/>
 *         <element name="journalpostnummer" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journalpostnummer" minOccurs="0"/>
 *         <element name="journalposttype" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journalposttype"/>
 *         <element name="journalstatus" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journalstatus"/>
 *         <element name="journaldato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journaldato" minOccurs="0"/>
 *         <element name="dokumentetsDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}dokumentetsDato" minOccurs="0"/>
 *         <element name="mottattDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}mottattDato" minOccurs="0"/>
 *         <element name="sendtDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}sendtDato" minOccurs="0"/>
 *         <element name="forfallsdato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}forfallsdato" minOccurs="0"/>
 *         <element name="offentlighetsvurdertDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}offentlighetsvurdertDato" minOccurs="0"/>
 *         <element name="antallVedlegg" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}antallVedlegg" minOccurs="0"/>
 *         <element name="utlaantDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}utlaantDato" minOccurs="0"/>
 *         <element name="utlaantTil" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}utlaantTil" minOccurs="0"/>
 *         <element name="journalenhet" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}journalenhet" minOccurs="0"/>
 *         <element name="avskrivning" type="{http://www.arkivverket.no/standarder/noark5/arkivmelding}avskrivning" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="dokumentflyt" type="{http://www.arkivverket.no/standarder/noark5/arkivmelding}dokumentflyt" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="presedens" type="{http://www.arkivverket.no/standarder/noark5/arkivmelding}presedens" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "journalpost", propOrder = {
    "journalaar",
    "journalsekvensnummer",
    "journalpostnummer",
    "journalposttype",
    "journalstatus",
    "journaldato",
    "dokumentetsDato",
    "mottattDato",
    "sendtDato",
    "forfallsdato",
    "offentlighetsvurdertDato",
    "antallVedlegg",
    "utlaantDato",
    "utlaantTil",
    "journalenhet",
    "avskrivning",
    "dokumentflyt",
    "presedens"
})
public class Journalpost
    extends Registrering
{

    protected BigInteger journalaar;
    protected BigInteger journalsekvensnummer;
    protected BigInteger journalpostnummer;
    @XmlElement(required = true)
    protected String journalposttype;
    @XmlElement(required = true)
    protected String journalstatus;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar journaldato;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dokumentetsDato;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mottattDato;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sendtDato;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar forfallsdato;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar offentlighetsvurdertDato;
    protected BigInteger antallVedlegg;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar utlaantDato;
    protected String utlaantTil;
    protected String journalenhet;
    protected List<Avskrivning> avskrivning;
    protected List<Dokumentflyt> dokumentflyt;
    protected List<Presedens> presedens;

    @Override
    public Journalpost useKorrespondansepart(Collection<Korrespondansepart> values) {
        if (values!= null) {
            getKorrespondansepart().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useKorrespondansepart(Korrespondansepart... values) {
        if (values!= null) {
            for (Korrespondansepart value: values) {
                getKorrespondansepart().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useKryssreferanse(Collection<Kryssreferanse> values) {
        if (values!= null) {
            getKryssreferanse().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useKryssreferanse(Kryssreferanse... values) {
        if (values!= null) {
            for (Kryssreferanse value: values) {
                getKryssreferanse().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useMerknad(Collection<Merknad> values) {
        if (values!= null) {
            getMerknad().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useMerknad(Merknad... values) {
        if (values!= null) {
            for (Merknad value: values) {
                getMerknad().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useVirksomhetsspesifikkeMetadata(Object value) {
        setVirksomhetsspesifikkeMetadata(value);
        return this;
    }

    @Override
    public Journalpost useOppbevaringssted(Collection<String> values) {
        if (values!= null) {
            getOppbevaringssted().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useOppbevaringssted(String... values) {
        if (values!= null) {
            for (String value: values) {
                getOppbevaringssted().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useDokumentmedium(String value) {
        setDokumentmedium(value);
        return this;
    }

    @Override
    public Journalpost useForfatter(Collection<String> values) {
        if (values!= null) {
            getForfatter().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useForfatter(String... values) {
        if (values!= null) {
            for (String value: values) {
                getForfatter().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useNoekkelord(Collection<String> values) {
        if (values!= null) {
            getNoekkelord().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useNoekkelord(String... values) {
        if (values!= null) {
            for (String value: values) {
                getNoekkelord().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useBeskrivelse(String value) {
        setBeskrivelse(value);
        return this;
    }

    @Override
    public Journalpost useOffentligTittel(String value) {
        setOffentligTittel(value);
        return this;
    }

    @Override
    public Journalpost useTittel(String value) {
        setTittel(value);
        return this;
    }

    @Override
    public Journalpost useRegistreringsID(String value) {
        setRegistreringsID(value);
        return this;
    }

    @Override
    public Journalpost useDokumentbeskrivelse(Collection<Dokumentbeskrivelse> values) {
        if (values!= null) {
            getDokumentbeskrivelse().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost useDokumentbeskrivelse(Dokumentbeskrivelse... values) {
        if (values!= null) {
            for (Dokumentbeskrivelse value: values) {
                getDokumentbeskrivelse().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useGradering(Gradering value) {
        setGradering(value);
        return this;
    }

    @Override
    public Journalpost useSkjerming(Skjerming value) {
        setSkjerming(value);
        return this;
    }

    @Override
    public Journalpost usePart(Collection<Part> values) {
        if (values!= null) {
            getPart().addAll(values);
        }
        return this;
    }

    @Override
    public Journalpost usePart(Part... values) {
        if (values!= null) {
            for (Part value: values) {
                getPart().add(value);
            }
        }
        return this;
    }

    @Override
    public Journalpost useReferanseArkivdel(String value) {
        setReferanseArkivdel(value);
        return this;
    }

    @Override
    public Journalpost useReferanseForelderMappe(String value) {
        setReferanseForelderMappe(value);
        return this;
    }

    @Override
    public Journalpost useArkivertAv(String value) {
        setArkivertAv(value);
        return this;
    }

    @Override
    public Journalpost useArkivertDato(XMLGregorianCalendar value) {
        setArkivertDato(value);
        return this;
    }

    @Override
    public Journalpost useOpprettetAv(String value) {
        setOpprettetAv(value);
        return this;
    }

    @Override
    public Journalpost useOpprettetDato(XMLGregorianCalendar value) {
        setOpprettetDato(value);
        return this;
    }

    @Override
    public Journalpost useSystemID(SystemID value) {
        setSystemID(value);
        return this;
    }

    /**
     * Gets the value of the journalaar property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJournalaar() {
        return journalaar;
    }

    /**
     * Sets the value of the journalaar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJournalaar(BigInteger value) {
        this.journalaar = value;
    }

    public Journalpost useJournalaar(BigInteger value) {
        setJournalaar(value);
        return this;
    }

    /**
     * Gets the value of the journalsekvensnummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJournalsekvensnummer() {
        return journalsekvensnummer;
    }

    /**
     * Sets the value of the journalsekvensnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJournalsekvensnummer(BigInteger value) {
        this.journalsekvensnummer = value;
    }

    public Journalpost useJournalsekvensnummer(BigInteger value) {
        setJournalsekvensnummer(value);
        return this;
    }

    /**
     * Gets the value of the journalpostnummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getJournalpostnummer() {
        return journalpostnummer;
    }

    /**
     * Sets the value of the journalpostnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setJournalpostnummer(BigInteger value) {
        this.journalpostnummer = value;
    }

    public Journalpost useJournalpostnummer(BigInteger value) {
        setJournalpostnummer(value);
        return this;
    }

    /**
     * Gets the value of the journalposttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalposttype() {
        return journalposttype;
    }

    /**
     * Sets the value of the journalposttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalposttype(String value) {
        this.journalposttype = value;
    }

    public Journalpost useJournalposttype(String value) {
        setJournalposttype(value);
        return this;
    }

    /**
     * Gets the value of the journalstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalstatus() {
        return journalstatus;
    }

    /**
     * Sets the value of the journalstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalstatus(String value) {
        this.journalstatus = value;
    }

    public Journalpost useJournalstatus(String value) {
        setJournalstatus(value);
        return this;
    }

    /**
     * Gets the value of the journaldato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getJournaldato() {
        return journaldato;
    }

    /**
     * Sets the value of the journaldato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setJournaldato(XMLGregorianCalendar value) {
        this.journaldato = value;
    }

    public Journalpost useJournaldato(XMLGregorianCalendar value) {
        setJournaldato(value);
        return this;
    }

    /**
     * Gets the value of the dokumentetsDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDokumentetsDato() {
        return dokumentetsDato;
    }

    /**
     * Sets the value of the dokumentetsDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDokumentetsDato(XMLGregorianCalendar value) {
        this.dokumentetsDato = value;
    }

    public Journalpost useDokumentetsDato(XMLGregorianCalendar value) {
        setDokumentetsDato(value);
        return this;
    }

    /**
     * Gets the value of the mottattDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMottattDato() {
        return mottattDato;
    }

    /**
     * Sets the value of the mottattDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMottattDato(XMLGregorianCalendar value) {
        this.mottattDato = value;
    }

    public Journalpost useMottattDato(XMLGregorianCalendar value) {
        setMottattDato(value);
        return this;
    }

    /**
     * Gets the value of the sendtDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSendtDato() {
        return sendtDato;
    }

    /**
     * Sets the value of the sendtDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSendtDato(XMLGregorianCalendar value) {
        this.sendtDato = value;
    }

    public Journalpost useSendtDato(XMLGregorianCalendar value) {
        setSendtDato(value);
        return this;
    }

    /**
     * Gets the value of the forfallsdato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getForfallsdato() {
        return forfallsdato;
    }

    /**
     * Sets the value of the forfallsdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setForfallsdato(XMLGregorianCalendar value) {
        this.forfallsdato = value;
    }

    public Journalpost useForfallsdato(XMLGregorianCalendar value) {
        setForfallsdato(value);
        return this;
    }

    /**
     * Gets the value of the offentlighetsvurdertDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOffentlighetsvurdertDato() {
        return offentlighetsvurdertDato;
    }

    /**
     * Sets the value of the offentlighetsvurdertDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOffentlighetsvurdertDato(XMLGregorianCalendar value) {
        this.offentlighetsvurdertDato = value;
    }

    public Journalpost useOffentlighetsvurdertDato(XMLGregorianCalendar value) {
        setOffentlighetsvurdertDato(value);
        return this;
    }

    /**
     * Gets the value of the antallVedlegg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAntallVedlegg() {
        return antallVedlegg;
    }

    /**
     * Sets the value of the antallVedlegg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAntallVedlegg(BigInteger value) {
        this.antallVedlegg = value;
    }

    public Journalpost useAntallVedlegg(BigInteger value) {
        setAntallVedlegg(value);
        return this;
    }

    /**
     * Gets the value of the utlaantDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUtlaantDato() {
        return utlaantDato;
    }

    /**
     * Sets the value of the utlaantDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUtlaantDato(XMLGregorianCalendar value) {
        this.utlaantDato = value;
    }

    public Journalpost useUtlaantDato(XMLGregorianCalendar value) {
        setUtlaantDato(value);
        return this;
    }

    /**
     * Gets the value of the utlaantTil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtlaantTil() {
        return utlaantTil;
    }

    /**
     * Sets the value of the utlaantTil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtlaantTil(String value) {
        this.utlaantTil = value;
    }

    public Journalpost useUtlaantTil(String value) {
        setUtlaantTil(value);
        return this;
    }

    /**
     * Gets the value of the journalenhet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalenhet() {
        return journalenhet;
    }

    /**
     * Sets the value of the journalenhet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalenhet(String value) {
        this.journalenhet = value;
    }

    public Journalpost useJournalenhet(String value) {
        setJournalenhet(value);
        return this;
    }

    /**
     * Gets the value of the avskrivning property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the avskrivning property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvskrivning().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Avskrivning }
     * 
     * 
     * @return
     *     The value of the avskrivning property.
     */
    public List<Avskrivning> getAvskrivning() {
        if (avskrivning == null) {
            avskrivning = new ArrayList<>();
        }
        return this.avskrivning;
    }

    public Journalpost useAvskrivning(Collection<Avskrivning> values) {
        if (values!= null) {
            getAvskrivning().addAll(values);
        }
        return this;
    }

    public Journalpost useAvskrivning(Avskrivning... values) {
        if (values!= null) {
            for (Avskrivning value: values) {
                getAvskrivning().add(value);
            }
        }
        return this;
    }

    /**
     * Gets the value of the dokumentflyt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the dokumentflyt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDokumentflyt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dokumentflyt }
     * 
     * 
     * @return
     *     The value of the dokumentflyt property.
     */
    public List<Dokumentflyt> getDokumentflyt() {
        if (dokumentflyt == null) {
            dokumentflyt = new ArrayList<>();
        }
        return this.dokumentflyt;
    }

    public Journalpost useDokumentflyt(Collection<Dokumentflyt> values) {
        if (values!= null) {
            getDokumentflyt().addAll(values);
        }
        return this;
    }

    public Journalpost useDokumentflyt(Dokumentflyt... values) {
        if (values!= null) {
            for (Dokumentflyt value: values) {
                getDokumentflyt().add(value);
            }
        }
        return this;
    }

    /**
     * Gets the value of the presedens property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the presedens property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresedens().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Presedens }
     * 
     * 
     * @return
     *     The value of the presedens property.
     */
    public List<Presedens> getPresedens() {
        if (presedens == null) {
            presedens = new ArrayList<>();
        }
        return this.presedens;
    }

    public Journalpost usePresedens(Collection<Presedens> values) {
        if (values!= null) {
            getPresedens().addAll(values);
        }
        return this;
    }

    public Journalpost usePresedens(Presedens... values) {
        if (values!= null) {
            for (Presedens value: values) {
                getPresedens().add(value);
            }
        }
        return this;
    }

}
