//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kryssreferanse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="kryssreferanse">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="referanseTilKlasse" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}referanseTilKlasse" minOccurs="0"/>
 *         <element name="referanseTilMappe" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}referanseTilMappe" minOccurs="0"/>
 *         <element name="referanseTilRegistrering" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}referanseTilRegistrering" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kryssreferanse", propOrder = {
    "referanseTilKlasse",
    "referanseTilMappe",
    "referanseTilRegistrering"
})
public class Kryssreferanse {

    protected String referanseTilKlasse;
    protected String referanseTilMappe;
    protected String referanseTilRegistrering;

    /**
     * Gets the value of the referanseTilKlasse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferanseTilKlasse() {
        return referanseTilKlasse;
    }

    /**
     * Sets the value of the referanseTilKlasse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferanseTilKlasse(String value) {
        this.referanseTilKlasse = value;
    }

    public Kryssreferanse useReferanseTilKlasse(String value) {
        setReferanseTilKlasse(value);
        return this;
    }

    /**
     * Gets the value of the referanseTilMappe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferanseTilMappe() {
        return referanseTilMappe;
    }

    /**
     * Sets the value of the referanseTilMappe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferanseTilMappe(String value) {
        this.referanseTilMappe = value;
    }

    public Kryssreferanse useReferanseTilMappe(String value) {
        setReferanseTilMappe(value);
        return this;
    }

    /**
     * Gets the value of the referanseTilRegistrering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferanseTilRegistrering() {
        return referanseTilRegistrering;
    }

    /**
     * Sets the value of the referanseTilRegistrering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferanseTilRegistrering(String value) {
        this.referanseTilRegistrering = value;
    }

    public Kryssreferanse useReferanseTilRegistrering(String value) {
        setReferanseTilRegistrering(value);
        return this;
    }

}
