//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for merknad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="merknad">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="merknadstekst" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}merknadstekst"/>
 *         <element name="merknadstype" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}merknadstype" minOccurs="0"/>
 *         <element name="merknadsdato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}merknadsdato"/>
 *         <element name="merknadRegistrertAv" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}merknadRegistrertAv"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "merknad", propOrder = {
    "merknadstekst",
    "merknadstype",
    "merknadsdato",
    "merknadRegistrertAv"
})
public class Merknad {

    @XmlElement(required = true)
    protected String merknadstekst;
    protected String merknadstype;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar merknadsdato;
    @XmlElement(required = true)
    protected String merknadRegistrertAv;

    /**
     * Gets the value of the merknadstekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerknadstekst() {
        return merknadstekst;
    }

    /**
     * Sets the value of the merknadstekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerknadstekst(String value) {
        this.merknadstekst = value;
    }

    public Merknad useMerknadstekst(String value) {
        setMerknadstekst(value);
        return this;
    }

    /**
     * Gets the value of the merknadstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerknadstype() {
        return merknadstype;
    }

    /**
     * Sets the value of the merknadstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerknadstype(String value) {
        this.merknadstype = value;
    }

    public Merknad useMerknadstype(String value) {
        setMerknadstype(value);
        return this;
    }

    /**
     * Gets the value of the merknadsdato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMerknadsdato() {
        return merknadsdato;
    }

    /**
     * Sets the value of the merknadsdato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMerknadsdato(XMLGregorianCalendar value) {
        this.merknadsdato = value;
    }

    public Merknad useMerknadsdato(XMLGregorianCalendar value) {
        setMerknadsdato(value);
        return this;
    }

    /**
     * Gets the value of the merknadRegistrertAv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerknadRegistrertAv() {
        return merknadRegistrertAv;
    }

    /**
     * Sets the value of the merknadRegistrertAv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerknadRegistrertAv(String value) {
        this.merknadRegistrertAv = value;
    }

    public Merknad useMerknadRegistrertAv(String value) {
        setMerknadRegistrertAv(value);
        return this;
    }

}
