//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.arkivverket.standarder.noark5.arkivmelding.v2;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for skjerming complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="skjerming">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="tilgangsrestriksjon" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}tilgangsrestriksjon"/>
 *         <element name="skjermingshjemmel" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}skjermingshjemmel"/>
 *         <element name="skjermingMetadata" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}skjermingMetadata" maxOccurs="unbounded"/>
 *         <element name="skjermingDokument" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}skjermingDokument" minOccurs="0"/>
 *         <element name="skjermingsvarighet" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}skjermingsvarighet" minOccurs="0"/>
 *         <element name="skjermingOpphoererDato" type="{http://www.arkivverket.no/standarder/noark5/metadatakatalog}skjermingOpphoererDato" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "skjerming", propOrder = {
    "tilgangsrestriksjon",
    "skjermingshjemmel",
    "skjermingMetadata",
    "skjermingDokument",
    "skjermingsvarighet",
    "skjermingOpphoererDato"
})
public class Skjerming {

    @XmlElement(required = true)
    protected String tilgangsrestriksjon;
    @XmlElement(required = true)
    protected String skjermingshjemmel;
    @XmlElement(required = true)
    protected List<String> skjermingMetadata;
    protected String skjermingDokument;
    protected BigInteger skjermingsvarighet;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar skjermingOpphoererDato;

    /**
     * Gets the value of the tilgangsrestriksjon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTilgangsrestriksjon() {
        return tilgangsrestriksjon;
    }

    /**
     * Sets the value of the tilgangsrestriksjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTilgangsrestriksjon(String value) {
        this.tilgangsrestriksjon = value;
    }

    public Skjerming useTilgangsrestriksjon(String value) {
        setTilgangsrestriksjon(value);
        return this;
    }

    /**
     * Gets the value of the skjermingshjemmel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkjermingshjemmel() {
        return skjermingshjemmel;
    }

    /**
     * Sets the value of the skjermingshjemmel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkjermingshjemmel(String value) {
        this.skjermingshjemmel = value;
    }

    public Skjerming useSkjermingshjemmel(String value) {
        setSkjermingshjemmel(value);
        return this;
    }

    /**
     * Gets the value of the skjermingMetadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the skjermingMetadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkjermingMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the skjermingMetadata property.
     */
    public List<String> getSkjermingMetadata() {
        if (skjermingMetadata == null) {
            skjermingMetadata = new ArrayList<>();
        }
        return this.skjermingMetadata;
    }

    public Skjerming useSkjermingMetadata(Collection<String> values) {
        if (values!= null) {
            getSkjermingMetadata().addAll(values);
        }
        return this;
    }

    public Skjerming useSkjermingMetadata(String... values) {
        if (values!= null) {
            for (String value: values) {
                getSkjermingMetadata().add(value);
            }
        }
        return this;
    }

    /**
     * Gets the value of the skjermingDokument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkjermingDokument() {
        return skjermingDokument;
    }

    /**
     * Sets the value of the skjermingDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkjermingDokument(String value) {
        this.skjermingDokument = value;
    }

    public Skjerming useSkjermingDokument(String value) {
        setSkjermingDokument(value);
        return this;
    }

    /**
     * Gets the value of the skjermingsvarighet property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSkjermingsvarighet() {
        return skjermingsvarighet;
    }

    /**
     * Sets the value of the skjermingsvarighet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSkjermingsvarighet(BigInteger value) {
        this.skjermingsvarighet = value;
    }

    public Skjerming useSkjermingsvarighet(BigInteger value) {
        setSkjermingsvarighet(value);
        return this;
    }

    /**
     * Gets the value of the skjermingOpphoererDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSkjermingOpphoererDato() {
        return skjermingOpphoererDato;
    }

    /**
     * Sets the value of the skjermingOpphoererDato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSkjermingOpphoererDato(XMLGregorianCalendar value) {
        this.skjermingOpphoererDato = value;
    }

    public Skjerming useSkjermingOpphoererDato(XMLGregorianCalendar value) {
        setSkjermingOpphoererDato(value);
        return this;
    }

}
