//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package no.nav.avtaltmelding.trygderetten.v1;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for navMappe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="navMappe">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="saksnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "navMappe", propOrder = {
    "saksnummer"
})
@XmlRootElement
public class NavMappe {

    @XmlElement(required = true)
    protected String saksnummer;

    /**
     * Gets the value of the saksnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksnummer() {
        return saksnummer;
    }

    /**
     * Sets the value of the saksnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksnummer(String value) {
        this.saksnummer = value;
    }

    public NavMappe useSaksnummer(String value) {
        setSaksnummer(value);
        return this;
    }

}
