//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.nav.no/avtaltmelding/trygderetten", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @jakarta.xml.bind.annotation.XmlNs(prefix = "nav", namespaceURI = "http://www.nav.no/avtaltmelding/trygderetten")
})
package no.nav.avtaltmelding.trygderetten.v1;
