TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

SAF_SCOPE: dev-fss.teamdokumenthandtering.saf-q2

DOKARKIV_SCOPE: dev-fss.teamdokumenthandtering.dokarkiv-q2/

JOARK_SERVICE_URL: https://dokarkiv-q2.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
DOKDIST_SERVICE_URL: https://dokdistfordeling.dev-fss-pub.nais.io/rest/v1/distribuerjournalpost

spring:
  datasource:
    hikari:
      maximum-pool-size: 5