SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest

NAIS_CLUSTER_NAME: local
AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
STS_APIKEY: 789

SAF_BASE_URL: local
SAF_SCOPE: uu-id
nais:
  cluster:
    name: local

NAIS_DATABASE_KABAL_API_KABAL_API_USERNAME: klage
NAIS_DATABASE_KABAL_API_KABAL_API_PASSWORD: klage
NAIS_DATABASE_KABAL_API_KABAL_API_DATABASE: kabal-document
NAIS_DATABASE_KABAL_API_KABAL_API_HOST: localhost
NAIS_DATABASE_KABAL_API_KABAL_API_PORT: 5432

JOARK_SERVICE_URL: http://localhost:1234
DOKDIST_SERVICE_URL: TODO
DOKDIST_APIKEY: TODO