TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b

SAF_BASE_URL: https://saf.prod-fss-pub.nais.io/
SAF_SCOPE: prod-fss.teamdokumenthandtering.saf

DOKARKIV_SCOPE: prod-fss.teamdokumenthandtering.dokarkiv/

JOARK_SERVICE_URL: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
DOKDIST_SERVICE_URL: https://dokdistfordeling.prod-fss-pub.nais.io/rest/v1/distribuerjournalpost

PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api

