ingresses:
  - https://kabal-document.dev.intern.nav.no
externalHosts:
  - host: login.microsoftonline.com
  - host: hooks.slack.com
  - host: unleash.nais.io
  - host: saf.dev-fss-pub.nais.io
  - host: pdl-api.dev-fss-pub.nais.io
springProfile: dev-gcp
tenant: trygdeetaten.no
db_tier: db-custom-1-3840
db_size: 10
db_ha: true
envs:
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx2048m"
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
